[package]
name = "solve_rs"
version = "0.0.1"
authors = ["matthew dunn <mshieldsdunn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.0"